---
title: "STA3115_homework1"
author: "Jaehun Shon"
date: "2024-09-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(readr);library(tidyverse);library(ggplot2);library(patchwork);library(gridExtra);library(knitr)
billboard <- read_csv("billboard.csv")
billboard
```

## Problem 1: Splitting the "time" variable

```{r}
billboard %>% 
  separate(time, into = c("minutes", "seconds", "mm"), sep = ":") %>% 
  .[, c("year", "artist.inverted", "track", "minutes", "seconds")] -> billboard.1

billboard.1 %>%
  head(10) %>%
  kable(col.names = c("Year", "Artist", "Track", "Minutes", "Seconds"),
        caption = "Top 10 rows of Billboard Data",
        format = "markdown")
```
## Problem 2: Creating a new time variable and histogram

```{r}
billboard.1 |> 
  mutate(time_in_min = as.numeric(minutes) + as.numeric(seconds) / 60) -> timevar

t <- timevar$time_in_min
description <- data.frame(
  Statistic = c("Mean", "Sd", "Median", "IQR", "Min", "Max"),
  Value = c(mean(t), sd(t), median(t), IQR(t), range(t)) %>% round(., 3)
) %>% t

histplot <- ggplot(timevar, aes(x = time_in_min)) +
  geom_histogram(fill = "skyblue", color = "blue", binwidth = 0.35) +
  labs(x = "Length of the song in minutes",
       y = "Frequency")

table_grob <- tableGrob(description)
final_plot <- grid.arrange(histplot, table_grob, nrow = 2, heights = c(3/4, 1/4))
```

## Problem 3: Summary statistics by weeks on chart

```{r, echo=FALSE}
billboard %>%
  separate(time, into = c("minutes", "seconds", "mm"), sep = ":") %>%
  select(year, artist.inverted, minutes, seconds, x16th.week) %>%
  mutate(time_in_min = as.numeric(minutes) + as.numeric(seconds) / 60) -> billboard.2

a <- billboard.2 %>% .[is.na(.[, 'x16th.week']),] %>% pull(time_in_min) # below 15
b <- billboard.2 %>% .[!is.na(.[, 'x16th.week']),] %>% pull(time_in_min) # more than 15

compare.dt <- tibble(
  Statistic = c("Mean", "Standard Deviation", "Median", "IQR"),
  `Below 15 weeks` = c(mean(a), sd(a), median(a), IQR(a)),
  `More than 15 weeks` = c(mean(b), sd(b), median(b), IQR(b))
)

compare.dt %>%
  kable(col.names = c("Statistic", "Below 15 weeks", "More than 15 weeks"),
        caption = "Comparison of Statistics for Below 15 weeks and More than 15 weeks",
        format = "markdown")
```

## Problem 4: Comparing song length distribution

```{r}
plot1 <- ggplot(billboard.2, aes(x = time_in_min)) +
  geom_density(aes(fill = ifelse(!is.na(x16th.week), "More than 15 weeks", "Below 15 weeks"),
                   color = ifelse(!is.na(x16th.week), "More than 15 weeks", "Below 15 weeks")),
               alpha = 0.7, adjust = 0.7) +
  labs(x = "Length of the song in minutes", y = "Density", 
       fill = "", color = "") +
  scale_fill_manual(values = c("More than 15 weeks" = "skyblue", "Below 15 weeks" = "pink")) +
  scale_color_manual(values = c("More than 15 weeks" = "blue", "Below 15 weeks" = "red")) +
  theme_minimal()


qq.df <- as.data.frame(qqplot(a, b, plot.it = FALSE))
plot2 <-ggplot(qq.df, aes(x = x, y = y)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "black") +
  labs(x = "Below 15 weeks", y = "More than 15 weeks",
       title = "QQ Plot: Below 15 weeks vs. More than 15 weeks") +
  xlim(range(c(a, b))) +
  ylim(range(c(a, b))) +
  theme_minimal()

pp <- plot1 + plot2
```

## Problem 5: Comparing to the Normal distribution

```{r}
qq_plot <- ggplot() +
  stat_qq(data = billboard.2 %>% filter(!is.na(x16th.week)),
          aes(sample = time_in_min)) +
  stat_qq_line(data = billboard.2 %>% filter(!is.na(x16th.week)),
               aes(sample = time_in_min), linewidth = 0.5) +
  geom_abline(aes(intercept = mean(b), slope = 0), color = 'red', linewidth = 0.1) +
  labs(x = "theoretical", y = "sample", title = 'Normal qq plot & Histogram (More than 15 weeks)')
  
hist_plot <- ggplot() +
  geom_histogram(data = billboard.2 %>% filter(!is.na(x16th.week)), 
                 aes(x = time_in_min),
                 binwidth = 0.5, fill = "skyblue", color = "blue") +
  coord_flip() +
  labs(x = "", y = "time in minutes")

qq_plot + hist_plot
```

```{r}
qq_plot <- ggplot() +
  stat_qq(data = billboard.2 %>% filter(is.na(x16th.week)),
          aes(sample = time_in_min)) +
  stat_qq_line(data = billboard.2 %>% filter(is.na(x16th.week)),
               aes(sample = time_in_min), linewidth = 0.5) +
  geom_abline(aes(intercept = mean(a), slope = 0), color = 'red', linewidth = 0.1) +
  labs(x = "theoretical", y = "sample", title = 'Normal qq plot & Histogram (Below 15 weeks)')
  
hist_plot <- ggplot() +
  geom_histogram(data = billboard.2 %>% filter(!is.na(x16th.week)), 
                 aes(x = time_in_min),
                 binwidth = 0.5, fill = "pink", color = "red") +
  coord_flip() +
  labs(x = "", y = "time in minutes")

qq_plot + hist_plot
```